spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lavaja?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: GbLrtqUmIH869ePk

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /doc.html